[tool.poetry]
name = "齿轮和v带设计计算方法"
version = "0.1.0"
description = ""
authors = ["dream同学0 <10135984+o19859860010@user.noreply.gitee.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
